env:
  node: true
plugins:
  - import
extends:   
  - 'airbnb-base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0